config/routes.rb
Rails.application.routes.draw do

  namespace :spider do
    namespace :admin do
      resources :spider_works, shallow: true do
        get 'add_item/:item' => :add_item, on: :collection, as: :add_item
        get 'remove_item/:item' => :remove_item, on: :collection, as: :remove_item
        patch :run, on: :member
        resources :spider_caches
        resources :spider_resources
      end
    end
  end

end

app/models/fail_url.rb
module TheSpider
  class FailUrl < ApplicationRecord
    attribute :url, type: String
    attribute :source, type: String
    attribute :flag, type: String

  end
end

app/models/spider/model/spider_cache.rb
class SpiderCache < ApplicationRecord
  belongs_to :spider_work

  def parser
    @parser ||= work.parser.new(self.body)
  end

  def run

  end

end

app/models/spider/model/spider_fail.rb
class SpiderFail < ApplicationRecord
  attribute :url, :string
  attribute :source, :string
  attribute :flag, :string

  belongs_to :spider_work


end

app/models/spider/model/spider_resource.rb
class SpiderResource < ApplicationRecord
  belongs_to :spider_work


end

app/models/spider/model/spider_session.rb
class SpiderSession < ApplicationRecord
  attribute :name, :string
  attribute :password, :string
  attribute :domain, :string
  attribute :value, :string

end

app/models/spider/model/spider_work.rb
class SpiderWork < ApplicationRecord
  has_many :spider_caches, dependent: :delete_all
  has_many :spider_resources, dependent: :delete_all

  accepts_nested_attributes_for :spider_resources, allow_destroy: true, reject_if: :all_blank

  def spider
    @spider ||= ApplicationSpider.new
  end

  def run
    ApplicationSpider.crawl!
  end

  def parser
    @parser ||= self.parser_name.to_s.safe_constantize
  end

  def parse
    locals.each do |local|
      local.run
    end
  end


end

app/models/the_spider/application_record.rb
module TheSpider
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/the_spider/cookie.rb
module TheSpider
  class Cookie < ApplicationRecord
    attribute :name, type: String
    attribute :password, type: String
    attribute :domain, type: String
    attribute :value, type: String

  end
end

app/models/the_spider/failed_url.rb
module TheSpider
  class FailedUrl < ApplicationRecord
    attribute :url, type: String
    attribute :source, type: String
    attribute :flag, type: String
  end
end

app/models/the_spider/local.rb
module TheSpider
  class Local < ApplicationRecord
    belongs_to :work

    def parser
      @parser ||= work.parser.new(self.body)
    end

    def run

    end

  end
end

app/models/the_spider/work.rb
module TheSpider
  class Work < ApplicationRecord
    has_many :locals

    def resource
      @resource ||= Resource.new(self)
    end

    def run
      @resource.run
    end

    def parser
      @parser ||= self.parser_name.to_s.safe_constantize
    end

    def parse
      locals.each do |local|
        local.run
      end
    end

  end
end

app/controllers/spider/admin/base_controller.rb
class Spider::Admin::BaseController < RailsSpider.config.admin_class.constantize

end

app/controllers/spider/admin/spider_works_controller.rb
class Spider::Admin::SpiderWorksController < Spider::Admin::BaseController
  before_action :set_spider_work, only: [:show, :edit, :update, :destroy]

  def index
    @spider_works = SpiderWork.page(params[:page])
  end

  def new
    @spider_work = SpiderWork.new
    @spider_work.spider_resources.build
  end

  def create
    @spider_work = SpiderWork.new(spider_work_params)

    if @spider_work.save
      redirect_to admin_spider_works_url, notice: 'Spider work was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
    if @spider_work.spider_resources.count == 0
      @spider_work.spider_resources.build
    end
  end

  def update
    if @spider_work.update(spider_work_params)
      redirect_to admin_spider_works_url, notice: 'Spider work was successfully updated.'
    else
      render :edit
    end
  end

  def add_item
    @spider_work = SpiderWork.new
    @spider_work.spider_resources.build
  end

  def remove_item

  end

  def destroy
    @spider_work.destroy
    redirect_to admin_spider_works_url, notice: 'Spider work was successfully destroyed.'
  end

  private
  def set_spider_work
    @spider_work = SpiderWork.find(params[:id])
  end

  def spider_work_params
    params.fetch(:spider_work, {}).permit(
      :name,
      :host,
      :list_path,
      :item_path,
      :page_params,
      spider_resources_attributes: {}
    )
  end

end

app/controllers/the_spider/application_controller.rb
module RailsSpider
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    default_form_builder 'RailsSpiderBuilder' do |config|

    end

  end
end

app/views/spider/admin/spider_works/_form.html.erb
<%= form_with model: [:admin, @spider_work], local: true do |f| %>
  <%= render 'shared/error_messages', target: @spider_work %>
  <%= f.text_field :name %>
  <%= f.text_field :host %>
  <%= f.text_field :list_path %>
  <%= f.text_field :item_path %>
  <%= f.text_field :page_params %>
  <%= f.fields :spider_resources, on: { wrapper_all: false, label: false, placeholder: true }, css: { wrapper_input: 'two wide field' } do |ef| %>
    <%= render partial: 'item_form', locals: { ef: ef } %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/spider/admin/spider_works/_item_field.html.erb
<%= f.fields :spider_resources, child_index: index, on: { wrapper_all: false, label: false, placeholder: true }, css: { wrapper_input: 'two wide field' } do |ef| %>
  <%= render partial: 'item_form', locals: { ef: ef } %>
<% end %>

app/views/spider/admin/spider_works/_item_form.html.erb
<div class="inline fields" id="spider_work_spider_resources_<%= ef.index %>" data-title="spider_work_spider_resources">
  <% if ef.index == 0 %>
    <%= ef.options[:parent_builder].label :spider_resources %>
  <% else %>
    <label class="six wide field"></label>
  <% end %>
  
  <%= ef.text_field :code %>
  <%= ef.text_field :xpath %>
  <%= ef.text_field :css %>
  
  <div class="field">
    <%= link_to add_item_admin_spider_works_path('item', index: ef.index), data: { title: 'add_item' }, remote: true do %>
      <i class="plus circle icon"></i>
    <% end %>
    <% if ef.object.id %>
      <%= ef.check_box :_destroy, { on: { offset: false }, css: { wrapper_checkbox: 'ui checkbox' }, checked: true }, 0, 1 %>
    <% else %>
      <%= link_to remove_item_admin_spider_works_path('item', index: ef.index), remote: true do %>
        <i class="minus circle icon"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spider/admin/spider_works/_search_form.html.erb
<%= search_form_with model: SpiderWork.new do |f| %>
  <div class="fields">
    <%= f.text_field :name %>
    <%= f.submit 'Search' %>
  </div>
<% end %>

app/views/spider/admin/spider_works/add_item.js.erb
<% form_object = default_form_object(@spider_work, on: { wrapper_id: true }) %>

var template = '<%= j(render partial: 'item_field', locals: { f: form_object, index: UidHelper.sec_uuid }) %>'

$('#spider_work_spider_resources_<%= params[:index] %>').after(template);

$('[data-title="spider_work_spider_resources"]').dropdown({
  placeholder: true
});

app/views/spider/admin/spider_works/edit.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', admin_spider_works_path, class: 'section' %>
  <div class="divider">/</div>
  <div class="active section">Edit</div>
</div>

<div class="ui segment">
  <%= render 'form' %>
</div>

app/views/spider/admin/spider_works/index.html.erb
<div class="ui top attached borderless menu">
  <div class="header item">Spider Works</div>
  <div class="right menu">
    <div class="item">
      <%= link_to 'New Spider Work', new_admin_spider_work_path, class: 'ui teal button' %>
    </div>
  </div>
</div>

<div class="ui attached segment">
  <%= render 'search_form' %>
</div>

<table class="ui bottom attached table">
  <thead>
    <tr>
      <th><%= SpiderWork.human_attribute_name(:id) %></th>
      <th><%= SpiderWork.human_attribute_name(:name) %></th>
      <th><%= SpiderWork.human_attribute_name(:host) %></th>
      <th><%= SpiderWork.human_attribute_name(:list_path) %></th>
      <th><%= SpiderWork.human_attribute_name(:item_path) %></th>
      <th><%= SpiderWork.human_attribute_name(:page_params) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @spider_works.each do |spider_work| %>
    <tr>
      <td><%= spider_work.id %></td>
      <td><%= spider_work.name %></td>
      <td><%= spider_work.host %></td>
      <td><%= spider_work.list_path %></td>
      <td><%= spider_work.item_path %></td>
      <td><%= spider_work.page_params %></td>
      <td class="ui labels">
        <%= link_to admin_spider_work_path(spider_work), data: { tooltip: t('.show') }, class: 'ui blue mini icon button' do %>
          <i class="location arrow icon"></i>
        <% end %>
        <%= link_to edit_admin_spider_work_path(spider_work), data: { tooltip: t('.edit') }, class: 'ui pink mini icon button' do %>
          <i class="pencil alternate icon"></i>
        <% end %>
        <%= link_to admin_spider_work_path(spider_work), method: :delete, data: { tooltip: t('.destroy'), confirm: 'Are you sure?' }, class: 'ui red mini icon button' do %>
          <i class="times icon"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @spider_works %>

app/views/spider/admin/spider_works/new.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', admin_spider_works_path, class: 'section' %>
  <div class="divider">/</div>
  <div class="active section">Add</div>
</div>

<div class="ui segment">
  <%= render 'form' %>
</div>

app/views/spider/admin/spider_works/remove_item.js.erb
$('#spider_work_spider_resources_<%= params[:index] %>').remove();

app/views/spider/admin/spider_works/show.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', admin_spider_works_path, class: 'section' %>
  <div class="divider">/</div>
  <div class="active section">Show</div>
</div>

<table class="ui very basic large table">
  <tbody>
    <tr>
      <td class="right aligned"><%= SpiderWork.human_attribute_name(:name) %></td>
      <td><%= @spider_work.name %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= SpiderWork.human_attribute_name(:host) %></td>
      <td><%= @spider_work.host %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= SpiderWork.human_attribute_name(:list_path) %></td>
      <td><%= @spider_work.list_path %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= SpiderWork.human_attribute_name(:item_path) %></td>
      <td><%= @spider_work.item_path %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= SpiderWork.human_attribute_name(:page_params) %></td>
      <td><%= @spider_work.page_params %></td>
    </tr>
  </tbody>
</table>